"""Attribute validation statuses, severities, and stable issue types."""

from enum import StrEnum


class CandidateValidationStatus(StrEnum):
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    INVALID = "INVALID"
    NOT_VALIDATABLE = "NOT_VALIDATABLE"


class AttributeValidationResultStatus(StrEnum):
    ALL_VALID = "ALL_VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    INVALID_CANDIDATES_FOUND = "INVALID_CANDIDATES_FOUND"
    NO_VALIDATABLE_CANDIDATES = "NO_VALIDATABLE_CANDIDATES"


class ValidationIssueSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class ValidationIssueType(StrEnum):
    TYPE_INVALID = "TYPE_INVALID"
    NUMERIC_MIN_VIOLATION = "NUMERIC_MIN_VIOLATION"
    NUMERIC_MAX_VIOLATION = "NUMERIC_MAX_VIOLATION"
    ALLOWED_VALUE_VIOLATION = "ALLOWED_VALUE_VIOLATION"
    PATTERN_VIOLATION = "PATTERN_VIOLATION"
    UNIT_MISSING = "UNIT_MISSING"
    UNIT_UNSUPPORTED = "UNIT_UNSUPPORTED"
    NORMALIZATION_INVALID = "NORMALIZATION_INVALID"
    NORMALIZATION_NOT_CANONICAL = "NORMALIZATION_NOT_CANONICAL"
