"""Processing-job domain enumerations."""

from enum import StrEnum


class ProcessingJobType(StrEnum):
    SOURCE_PROCESSING = "SOURCE_PROCESSING"
    PDF_TEXT_EXTRACTION = "PDF_TEXT_EXTRACTION"
    PDF_TABLE_EXTRACTION = "PDF_TABLE_EXTRACTION"
    IMAGE_ANALYSIS = "IMAGE_ANALYSIS"
    IMAGE_OCR = "IMAGE_OCR"
    CSV_PROCESSING = "CSV_PROCESSING"
    PRODUCT_CLASSIFICATION = "PRODUCT_CLASSIFICATION"
    ATTRIBUTE_EXTRACTION = "ATTRIBUTE_EXTRACTION"
    ATTRIBUTE_NORMALIZATION = "ATTRIBUTE_NORMALIZATION"
    ATTRIBUTE_CONFLICT_DETECTION = "ATTRIBUTE_CONFLICT_DETECTION"


class ProcessingJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
