"""Stable classification vocabulary, resolution, and review enums."""

from enum import StrEnum


class VocabularySource(StrEnum):
    OBSERVED_DATASET = "OBSERVED_DATASET"
    LABELLED_OUTPUT = "LABELLED_OUTPUT"
    VERIFIED_EXTERNAL = "VERIFIED_EXTERNAL"
    HUMAN_APPROVED = "HUMAN_APPROVED"


class AbbreviationStatus(StrEnum):
    VERIFIED_OBSERVED = "VERIFIED_OBSERVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNSUPPORTED = "UNSUPPORTED"


class ProductTypeMatchMethod(StrEnum):
    EXPLICIT_PHRASE = "EXPLICIT_PHRASE"
    OBSERVED_VARIANT = "OBSERVED_VARIANT"
    OBSERVED_ABBREVIATION = "OBSERVED_ABBREVIATION"
    DESCRIPTION_PATTERN = "DESCRIPTION_PATTERN"
    MODEL_ASSISTED = "MODEL_ASSISTED"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"


class ClassificationReviewReason(StrEnum):
    PRODUCT_TYPE_UNKNOWN = "PRODUCT_TYPE_UNKNOWN"
    PRODUCT_TYPE_AMBIGUOUS = "PRODUCT_TYPE_AMBIGUOUS"
    PRODUCT_TYPE_GENERIC = "PRODUCT_TYPE_GENERIC"
    CLASSPATH_UNKNOWN = "CLASSPATH_UNKNOWN"
    CLASSPATH_MAPPING_WEAK = "CLASSPATH_MAPPING_WEAK"
    CLASSPATH_CONFLICT = "CLASSPATH_CONFLICT"


class ClasspathMappingSource(StrEnum):
    OFFICIAL_LABELLED_OUTPUT = "OFFICIAL_LABELLED_OUTPUT"
    HUMAN_VERIFIED_MAPPING = "HUMAN_VERIFIED_MAPPING"
