"""Completeness assessment and aggregate statuses."""

from enum import StrEnum


class AttributeCompletenessState(StrEnum):
    PRESENT = "PRESENT"
    PRESENT_WITH_TOLERANCE = "PRESENT_WITH_TOLERANCE"
    PRESENT_SINGLE_SOURCE = "PRESENT_SINGLE_SOURCE"
    CONFLICTED = "CONFLICTED"
    INDETERMINATE = "INDETERMINATE"
    INVALID_ONLY = "INVALID_ONLY"
    MISSING = "MISSING"


class AttributeCompletenessStatus(StrEnum):
    COMPLETE = "COMPLETE"
    COMPLETE_WITH_SINGLE_SOURCE = "COMPLETE_WITH_SINGLE_SOURCE"
    INCOMPLETE = "INCOMPLETE"
    CONFLICTED = "CONFLICTED"
    INDETERMINATE = "INDETERMINATE"
    NO_USABLE_ATTRIBUTES = "NO_USABLE_ATTRIBUTES"
