"""Enums for the isolated Unilog challenge adapter."""

from enum import StrEnum


class ManufacturerParseStatus(StrEnum):
    PARSED = "PARSED"
    UNPARSED = "UNPARSED"
    AMBIGUOUS = "AMBIGUOUS"
    MISSING = "MISSING"


class ResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    PARTIAL = "PARTIAL"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"
    MISSING = "MISSING"


class EvidenceSourceType(StrEnum):
    RAW_INPUT = "RAW_INPUT"
    OFFICIAL_LABELLED_OUTPUT_MAPPING = "OFFICIAL_LABELLED_OUTPUT_MAPPING"
    DETERMINISTIC_PARSE = "DETERMINISTIC_PARSE"
    OFFICIAL_MANUFACTURER_SOURCE = "OFFICIAL_MANUFACTURER_SOURCE"
    VALIDATED_MODEL_INFERENCE = "VALIDATED_MODEL_INFERENCE"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class EvidenceStrength(StrEnum):
    DIRECT = "DIRECT"
    DERIVED = "DERIVED"
    CORROBORATED = "CORROBORATED"
    INFERRED = "INFERRED"
    UNSUPPORTED = "UNSUPPORTED"


class ComparisonStatus(StrEnum):
    EXACT_MATCH = "EXACT_MATCH"
    NORMALIZED_MATCH = "NORMALIZED_MATCH"
    MISMATCH = "MISMATCH"
    EXPECTED_BLANK = "EXPECTED_BLANK"
    ACTUAL_BLANK = "ACTUAL_BLANK"
    BOTH_BLANK = "BOTH_BLANK"
    NOT_EVALUATED = "NOT_EVALUATED"


class AlignmentStatus(StrEnum):
    ALIGNED = "ALIGNED"
    NOT_FOUND = "NOT_FOUND"
    AMBIGUOUS_ALIGNMENT = "AMBIGUOUS_ALIGNMENT"


class DatasetSplit(StrEnum):
    TRAIN = "TRAIN"
    DEVELOPMENT = "DEVELOPMENT"
    EVALUATION = "EVALUATION"


class FieldPopulationStrategy(StrEnum):
    DIRECT_COPY = "DIRECT_COPY"
    DETERMINISTIC_PARSE = "DETERMINISTIC_PARSE"
    OBSERVED_MAPPING = "OBSERVED_MAPPING"
    ATTRIBUTE_DERIVED = "ATTRIBUTE_DERIVED"
    DESCRIPTION_CONSTRUCTED = "DESCRIPTION_CONSTRUCTED"
    MODEL_ASSISTED = "MODEL_ASSISTED"
    EXTERNAL_ONLY = "EXTERNAL_ONLY"
    UNSUPPORTED = "UNSUPPORTED"


class FieldValidationStatus(StrEnum):
    VALID = "VALID"
    VALID_WITH_WARNING = "VALID_WITH_WARNING"
    INVALID = "INVALID"
    UNSUPPORTED = "UNSUPPORTED"
    MISSING = "MISSING"


class BatchRowStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
