"""Attribute selection and review-preparation enumerations."""

from enum import StrEnum


class AttributeSelectionStatus(StrEnum):
    AUTO_SELECTED = "AUTO_SELECTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NO_CANDIDATE = "NO_CANDIDATE"
    NO_VALID_CANDIDATE = "NO_VALID_CANDIDATE"


class ProductReviewStatus(StrEnum):
    READY_FOR_AUTO_APPROVAL = "READY_FOR_AUTO_APPROVAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class SelectionReasonCode(StrEnum):
    MULTI_SOURCE_EXACT_AGREEMENT = "MULTI_SOURCE_EXACT_AGREEMENT"
    MULTI_SOURCE_TOLERANCE_AGREEMENT = "MULTI_SOURCE_TOLERANCE_AGREEMENT"
    SINGLE_SOURCE_ONLY = "SINGLE_SOURCE_ONLY"
    VALUE_CONFLICT = "VALUE_CONFLICT"
    UNIT_INDETERMINATE = "UNIT_INDETERMINATE"
    MISSING_ATTRIBUTE = "MISSING_ATTRIBUTE"
    NO_VALID_CANDIDATE = "NO_VALID_CANDIDATE"
    VALIDATION_WARNING = "VALIDATION_WARNING"
    INSUFFICIENT_CORROBORATION = "INSUFFICIENT_CORROBORATION"
    OPTIONAL_ATTRIBUTE_UNRESOLVED = "OPTIONAL_ATTRIBUTE_UNRESOLVED"


class ReviewReasonSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    REQUIRED_REVIEW = "REQUIRED_REVIEW"
