"""Commerce catalog projection enumerations."""

from enum import StrEnum


class CatalogProjectionStatus(StrEnum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    BLOCKED = "BLOCKED"


class CatalogBlockingReason(StrEnum):
    PRODUCT_NAME_MISSING = "PRODUCT_NAME_MISSING"
    PRODUCT_CATEGORY_UNCLASSIFIED = "PRODUCT_CATEGORY_UNCLASSIFIED"
    PRODUCT_CATEGORY_MISMATCH = "PRODUCT_CATEGORY_MISMATCH"
    REVIEWED_ATTRIBUTES_MISSING = "REVIEWED_ATTRIBUTES_MISSING"
    REVIEWED_ATTRIBUTE_LINEAGE_INVALID = "REVIEWED_ATTRIBUTE_LINEAGE_INVALID"
    REQUIRED_ATTRIBUTE_MISSING = "REQUIRED_ATTRIBUTE_MISSING"
    REQUIRED_ATTRIBUTE_INVALID = "REQUIRED_ATTRIBUTE_INVALID"


class CatalogWarningReason(StrEnum):
    MANUFACTURER_MISSING = "MANUFACTURER_MISSING"
    MODEL_NUMBER_MISSING = "MODEL_NUMBER_MISSING"
    DESCRIPTION_MISSING = "DESCRIPTION_MISSING"
    OPTIONAL_ATTRIBUTES_UNRESOLVED = "OPTIONAL_ATTRIBUTES_UNRESOLVED"
    VALIDATION_WARNING_PRESENT = "VALIDATION_WARNING_PRESENT"
    HUMAN_OVERRIDE_PRESENT = "HUMAN_OVERRIDE_PRESENT"
