"""Versioned built-in technical-attribute schemas for supported categories."""

from datetime import UTC, datetime

from app.domain.category_schemas.entities import (
    AttributeDefinition,
    AttributeValidationRules,
    CategoryAttributeSchema,
    UnitDefinition,
)
from app.domain.category_schemas.enums import AttributeDataType, CategoryAttributeSchemaStatus
from app.domain.products import ProductCategory

BUILTIN_SCHEMA_CREATED_AT = datetime(2026, 1, 1, tzinfo=UTC)


def _unit(symbol: str, dimension: str) -> UnitDefinition:
    return UnitDefinition(symbol=symbol, canonical=symbol, dimension=dimension)


def _attribute(
    name: str,
    display_name: str,
    description: str,
    data_type: AttributeDataType,
    required: bool,
    order: int,
    *,
    units: tuple[UnitDefinition, ...] = (),
    aliases: tuple[str, ...] = (),
    examples: tuple[str, ...] = (),
    rules: AttributeValidationRules | None = None,
) -> AttributeDefinition:
    return AttributeDefinition(
        attribute_id=name,
        canonical_name=name,
        display_name=display_name,
        description=description,
        data_type=data_type,
        required=required,
        allowed_units=units,
        aliases=aliases,
        example_values=examples,
        validation_rules=rules or AttributeValidationRules(),
        display_order=order,
    )


def induction_motor_schema_v1() -> CategoryAttributeSchema:
    attributes = (
        _attribute(
            "ratedPower",
            "Rated Power",
            "Rated mechanical output power of the motor.",
            AttributeDataType.NUMBER,
            True,
            1,
            units=(_unit("kW", "power"), _unit("W", "power"), _unit("hp", "power")),
            aliases=("rated power", "motor power", "rated output", "output power", "power output"),
            examples=("5.5 kW", "7.5 kW"),
        ),
        _attribute(
            "voltage",
            "Voltage",
            "Rated electrical supply voltage.",
            AttributeDataType.NUMBER,
            True,
            2,
            units=(_unit("V", "voltage"),),
            aliases=("voltage", "rated voltage", "supply voltage"),
            examples=("415 V",),
        ),
        _attribute(
            "frequency",
            "Frequency",
            "Rated electrical supply frequency.",
            AttributeDataType.NUMBER,
            True,
            3,
            units=(_unit("Hz", "frequency"),),
            aliases=("frequency", "rated frequency", "supply frequency"),
            examples=("50 Hz",),
        ),
        _attribute(
            "speedRpm",
            "Speed RPM",
            "Rated rotational speed of the motor shaft.",
            AttributeDataType.INTEGER,
            True,
            4,
            units=(_unit("rpm", "rotational speed"),),
            aliases=("speed", "rated speed", "motor speed", "rpm", "rotational speed"),
            examples=("1450 rpm",),
        ),
        _attribute(
            "phase",
            "Phase",
            "Number of electrical supply phases.",
            AttributeDataType.INTEGER,
            True,
            5,
            aliases=("phase", "phases", "number of phases"),
            examples=("3",),
            rules=AttributeValidationRules(allowed_values=("1", "3")),
        ),
        _attribute(
            "current",
            "Current",
            "Rated full-load electrical current.",
            AttributeDataType.NUMBER,
            False,
            6,
            units=(_unit("A", "current"),),
            aliases=("current", "rated current", "full load current"),
            examples=("10.8 A",),
        ),
        _attribute(
            "efficiency",
            "Efficiency",
            "Rated motor efficiency.",
            AttributeDataType.NUMBER,
            False,
            7,
            units=(_unit("%", "ratio"),),
            aliases=("efficiency", "rated efficiency"),
            examples=("91.2 %",),
            rules=AttributeValidationRules(min_value=0, max_value=100),
        ),
        _attribute(
            "powerFactor",
            "Power Factor",
            "Ratio of real power to apparent power.",
            AttributeDataType.NUMBER,
            False,
            8,
            aliases=("power factor", "cos phi", "cosφ"),
            examples=("0.86",),
            rules=AttributeValidationRules(min_value=0, max_value=1),
        ),
        _attribute(
            "insulationClass",
            "Insulation Class",
            "Thermal class of winding insulation.",
            AttributeDataType.TEXT,
            False,
            9,
            aliases=("insulation class", "ins class"),
            examples=("F",),
        ),
        _attribute(
            "ipRating",
            "IP Rating",
            "Ingress-protection rating of the enclosure.",
            AttributeDataType.TEXT,
            False,
            10,
            aliases=("ip rating", "degree of protection", "protection class"),
            examples=("IP55", "IP66"),
            rules=AttributeValidationRules(pattern=r"^IP[0-9]{2}[A-Za-z]?$"),
        ),
        _attribute(
            "frameSize",
            "Frame Size",
            "Standardized motor frame designation.",
            AttributeDataType.TEXT,
            False,
            11,
            aliases=("frame", "frame size"),
            examples=("132S",),
        ),
        _attribute(
            "duty",
            "Duty",
            "Declared motor duty classification.",
            AttributeDataType.TEXT,
            False,
            12,
            aliases=("duty", "duty cycle", "duty type"),
            examples=("S1",),
        ),
        _attribute(
            "mountingType",
            "Mounting Type",
            "Mechanical mounting arrangement.",
            AttributeDataType.TEXT,
            False,
            13,
            aliases=("mounting", "mounting type", "mounting arrangement"),
            examples=("B3",),
        ),
    )
    return CategoryAttributeSchema.create(
        category=ProductCategory.INDUCTION_MOTOR,
        version=1,
        status=CategoryAttributeSchemaStatus.ACTIVE,
        description="Canonical induction-motor technical attributes, version 1.",
        attributes=attributes,
        now=BUILTIN_SCHEMA_CREATED_AT,
    )


def centrifugal_pump_schema_v1() -> CategoryAttributeSchema:
    attributes = (
        _attribute(
            "flowRate",
            "Flow Rate",
            "Rated volumetric delivery rate of the pump.",
            AttributeDataType.NUMBER,
            True,
            1,
            units=(
                _unit("m3/h", "volumetric flow"),
                _unit("L/min", "volumetric flow"),
                _unit("gpm", "volumetric flow"),
            ),
            aliases=(
                "flow",
                "flow rate",
                "capacity",
                "pump capacity",
                "rated flow",
                "delivery rate",
            ),
            examples=("100 m3/h",),
        ),
        _attribute(
            "head",
            "Head",
            "Rated energy head developed by the pump.",
            AttributeDataType.NUMBER,
            True,
            2,
            units=(_unit("m", "length"), _unit("ft", "length")),
            aliases=(
                "head",
                "total head",
                "delivery head",
                "rated head",
                "total dynamic head",
                "tdh",
            ),
            examples=("45 m",),
        ),
        _attribute(
            "maximumPressure",
            "Maximum Pressure",
            "Maximum declared pump working pressure.",
            AttributeDataType.NUMBER,
            False,
            3,
            units=(_unit("bar", "pressure"), _unit("psi", "pressure")),
            aliases=(
                "maximum pressure",
                "max pressure",
                "working pressure",
                "maximum working pressure",
            ),
            examples=("10 bar",),
        ),
        _attribute(
            "speedRpm",
            "Speed RPM",
            "Rated rotational speed of the pump.",
            AttributeDataType.INTEGER,
            False,
            4,
            units=(_unit("rpm", "rotational speed"),),
            aliases=("speed", "pump speed", "rated speed", "rpm"),
            examples=("2900 rpm",),
        ),
        _attribute(
            "ratedPower",
            "Rated Power",
            "Rated input or coupled motor power.",
            AttributeDataType.NUMBER,
            False,
            5,
            units=(_unit("kW", "power"), _unit("W", "power"), _unit("hp", "power")),
            aliases=("power", "rated power", "motor power", "input power"),
            examples=("11 kW",),
        ),
        _attribute(
            "efficiency",
            "Efficiency",
            "Rated hydraulic pump efficiency.",
            AttributeDataType.NUMBER,
            False,
            6,
            units=(_unit("%", "ratio"),),
            aliases=("efficiency", "pump efficiency"),
            examples=("78 %",),
            rules=AttributeValidationRules(min_value=0, max_value=100),
        ),
        _attribute(
            "suctionSize",
            "Suction Size",
            "Nominal suction connection size.",
            AttributeDataType.NUMBER,
            False,
            7,
            units=(_unit("mm", "length"), _unit("in", "length")),
            aliases=(
                "suction size",
                "suction diameter",
                "inlet size",
                "inlet diameter",
                "suction connection",
            ),
            examples=("100 mm",),
        ),
        _attribute(
            "dischargeSize",
            "Discharge Size",
            "Nominal discharge connection size.",
            AttributeDataType.NUMBER,
            False,
            8,
            units=(_unit("mm", "length"), _unit("in", "length")),
            aliases=(
                "discharge size",
                "discharge diameter",
                "outlet size",
                "outlet diameter",
                "discharge connection",
            ),
            examples=("80 mm",),
        ),
        _attribute(
            "impellerDiameter",
            "Impeller Diameter",
            "Nominal or trimmed impeller diameter.",
            AttributeDataType.NUMBER,
            False,
            9,
            units=(_unit("mm", "length"), _unit("in", "length")),
            aliases=("impeller diameter", "impeller size"),
            examples=("250 mm",),
        ),
        _attribute(
            "sealType",
            "Seal Type",
            "Type of shaft sealing arrangement.",
            AttributeDataType.TEXT,
            False,
            10,
            aliases=("seal", "seal type", "mechanical seal"),
            examples=("Mechanical seal",),
        ),
        _attribute(
            "material",
            "Material",
            "Primary pump material of construction.",
            AttributeDataType.TEXT,
            False,
            11,
            aliases=("material", "construction material", "material of construction", "moc"),
            examples=("Cast iron",),
        ),
        _attribute(
            "npshRequired",
            "NPSH Required",
            "Net positive suction head required by the pump.",
            AttributeDataType.NUMBER,
            False,
            12,
            units=(_unit("m", "length"), _unit("ft", "length")),
            aliases=("npsh", "npshr", "npsh required", "net positive suction head required"),
            examples=("3.2 m",),
        ),
    )
    return CategoryAttributeSchema.create(
        category=ProductCategory.CENTRIFUGAL_PUMP,
        version=1,
        status=CategoryAttributeSchemaStatus.ACTIVE,
        description="Canonical centrifugal-pump technical attributes, version 1.",
        attributes=attributes,
        now=BUILTIN_SCHEMA_CREATED_AT,
    )


def built_in_category_schemas() -> tuple[CategoryAttributeSchema, ...]:
    return (centrifugal_pump_schema_v1(), induction_motor_schema_v1())
