"""Evidence sources and review semantics for challenge identity resolution."""

from enum import StrEnum


class IdentityEvidenceSource(StrEnum):
    PART_MANUF = "PART_MANUF"
    E1_BRAND = "E1_BRAND"
    UNILOG_BRAND = "UNILOG_BRAND"
    DIB_BRAND = "DIB_BRAND"
    PART_DESC = "PART_DESC"
    OBSERVED_LABELLED_MAPPING = "OBSERVED_LABELLED_MAPPING"
    DATASET_REPETITION = "DATASET_REPETITION"
    PRODUCT_TYPE_CONTEXT = "PRODUCT_TYPE_CONTEXT"
    MODEL_ASSISTED = "MODEL_ASSISTED"


class IdentityReviewReason(StrEnum):
    SUPPLIER_ONLY_EVIDENCE = "SUPPLIER_ONLY_EVIDENCE"
    MANUFACTURER_AMBIGUOUS = "MANUFACTURER_AMBIGUOUS"
    MANUFACTURER_UNRESOLVED = "MANUFACTURER_UNRESOLVED"
    BRAND_AMBIGUOUS = "BRAND_AMBIGUOUS"
    BRAND_UNRESOLVED = "BRAND_UNRESOLVED"
    BRAND_FIELD_CONFLICT = "BRAND_FIELD_CONFLICT"
    DESCRIPTION_BRAND_WEAK = "DESCRIPTION_BRAND_WEAK"
    MPN_PREFIX_WEAK = "MPN_PREFIX_WEAK"
    ORGANIZATION_ROLE_AMBIGUOUS = "ORGANIZATION_ROLE_AMBIGUOUS"
