"""Candidate agreement and conflict detection enumerations."""

from enum import StrEnum


class AttributeConsensusStatus(StrEnum):
    SINGLE_CANDIDATE = "SINGLE_CANDIDATE"
    AGREEMENT = "AGREEMENT"
    AGREEMENT_WITH_TOLERANCE = "AGREEMENT_WITH_TOLERANCE"
    CONFLICT = "CONFLICT"
    INDETERMINATE = "INDETERMINATE"
    NO_VALID_CANDIDATES = "NO_VALID_CANDIDATES"


class AttributeConflictType(StrEnum):
    VALUE_CONFLICT = "VALUE_CONFLICT"
    UNIT_INDETERMINATE = "UNIT_INDETERMINATE"
    MIXED_VALIDITY = "MIXED_VALIDITY"
    MULTIPLE_VALUE_GROUPS = "MULTIPLE_VALUE_GROUPS"


class ConflictDetectionResultStatus(StrEnum):
    NO_CONFLICTS = "NO_CONFLICTS"
    CONFLICTS_FOUND = "CONFLICTS_FOUND"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    NO_COMPARABLE_ATTRIBUTES = "NO_COMPARABLE_ATTRIBUTES"
