"""Commerce catalog projection repository contract."""

from typing import Protocol
from uuid import UUID

from app.domain.catalog_projection import CommerceCatalogProjection


class CommerceCatalogProjectionRepository(Protocol):
    def create(self, result: CommerceCatalogProjection) -> CommerceCatalogProjection: ...
    def get_by_id(self, projection_id: UUID) -> CommerceCatalogProjection | None: ...
    def get_by_job_id(self, job_id: UUID) -> CommerceCatalogProjection | None: ...
    def get_by_materialization_id(
        self, materialization_id: UUID
    ) -> CommerceCatalogProjection | None: ...
    def get_latest_by_product_id(self, product_id: UUID) -> CommerceCatalogProjection | None: ...
