"""Attribute and unit normalization enumerations."""

from enum import StrEnum


class NormalizationStatus(StrEnum):
    NORMALIZED = "NORMALIZED"
    NORMALIZED_WITH_CONVERSION = "NORMALIZED_WITH_CONVERSION"
    UNIT_MISSING = "UNIT_MISSING"
    UNSUPPORTED_UNIT = "UNSUPPORTED_UNIT"
    INVALID_VALUE = "INVALID_VALUE"
    RAW_TEXT_PRESERVED = "RAW_TEXT_PRESERVED"


class AttributeNormalizationResultStatus(StrEnum):
    NORMALIZED = "NORMALIZED"
    NORMALIZED_WITH_WARNINGS = "NORMALIZED_WITH_WARNINGS"
    NO_CANDIDATES = "NO_CANDIDATES"


class UnitDimension(StrEnum):
    POWER = "POWER"
    VOLTAGE = "VOLTAGE"
    CURRENT = "CURRENT"
    FREQUENCY = "FREQUENCY"
    ROTATIONAL_SPEED = "ROTATIONAL_SPEED"
    PERCENT = "PERCENT"
    FLOW_RATE = "FLOW_RATE"
    LENGTH = "LENGTH"
    DIAMETER = "DIAMETER"
    PRESSURE = "PRESSURE"
