"""Stable observed-attribute vocabulary and resolution enums."""

from enum import StrEnum


class AttributeVocabularySource(StrEnum):
    OBSERVED_LABELLED_OUTPUT = "OBSERVED_LABELLED_OUTPUT"
    HUMAN_APPROVED = "HUMAN_APPROVED"


class AttributeExtractionMethod(StrEnum):
    EXPLICIT_PATTERN = "EXPLICIT_PATTERN"
    PRODUCT_TYPE_RULE = "PRODUCT_TYPE_RULE"
    MEASUREMENT_PARSE = "MEASUREMENT_PARSE"
    OBSERVED_MAPPING = "OBSERVED_MAPPING"
    MODEL_ASSISTED = "MODEL_ASSISTED"


class AttributeReviewReason(StrEnum):
    ATTRIBUTE_LABEL_UNKNOWN = "ATTRIBUTE_LABEL_UNKNOWN"
    ATTRIBUTE_VALUE_AMBIGUOUS = "ATTRIBUTE_VALUE_AMBIGUOUS"
    ATTRIBUTE_UNIT_AMBIGUOUS = "ATTRIBUTE_UNIT_AMBIGUOUS"
    ATTRIBUTE_CONFLICT = "ATTRIBUTE_CONFLICT"
    ATTRIBUTE_TYPE_CONTEXT_REQUIRED = "ATTRIBUTE_TYPE_CONTEXT_REQUIRED"
    ATTRIBUTE_LOW_CONFIDENCE = "ATTRIBUTE_LOW_CONFIDENCE"
    ATTRIBUTE_OVERFLOW = "ATTRIBUTE_OVERFLOW"
