"""Fixed Catalog Intelligence workflow state vocabulary."""

from enum import StrEnum


class CatalogWorkflowStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"


class CatalogWorkflowStageName(StrEnum):
    SOURCE_PROCESSING = "SOURCE_PROCESSING"
    PRODUCT_CLASSIFICATION = "PRODUCT_CLASSIFICATION"
    ATTRIBUTE_EXTRACTION = "ATTRIBUTE_EXTRACTION"
    ATTRIBUTE_NORMALIZATION = "ATTRIBUTE_NORMALIZATION"
    CONFLICT_DETECTION = "CONFLICT_DETECTION"
    COMPLETENESS = "COMPLETENESS"
    ATTRIBUTE_VALIDATION = "ATTRIBUTE_VALIDATION"
    ATTRIBUTE_SELECTION = "ATTRIBUTE_SELECTION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    REVIEWED_ATTRIBUTE_MATERIALIZATION = "REVIEWED_ATTRIBUTE_MATERIALIZATION"
    CATALOG_PROJECTION = "CATALOG_PROJECTION"
    PUBLISHING_READINESS = "PUBLISHING_READINESS"
    CATALOG_EXPORT = "CATALOG_EXPORT"
    AI_ENRICHMENT = "AI_ENRICHMENT"
    PRODUCT_INTELLIGENCE_SCORE = "PRODUCT_INTELLIGENCE_SCORE"


class CatalogWorkflowStageStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    WAITING = "WAITING"
    FAILED = "FAILED"


class CatalogWorkflowNextAction(StrEnum):
    NONE = "NONE"
    COMPLETE_PRODUCT_REVIEW = "COMPLETE_PRODUCT_REVIEW"
    RESUME_WORKFLOW = "RESUME_WORKFLOW"


class CatalogWorkflowSkipReason(StrEnum):
    DISABLED = "DISABLED"
    PROJECTION_BLOCKED = "PROJECTION_BLOCKED"
    ALREADY_READY_TO_PUBLISH = "ALREADY_READY_TO_PUBLISH"


TERMINAL_WORKFLOW_STATUSES = frozenset(
    {
        CatalogWorkflowStatus.FAILED,
        CatalogWorkflowStatus.COMPLETED,
        CatalogWorkflowStatus.COMPLETED_WITH_WARNINGS,
    }
)

TERMINAL_STAGE_STATUSES = frozenset(
    {
        CatalogWorkflowStageStatus.COMPLETED,
        CatalogWorkflowStageStatus.SKIPPED,
        CatalogWorkflowStageStatus.FAILED,
    }
)

OPTIONAL_STAGES = frozenset(
    {
        CatalogWorkflowStageName.CATALOG_EXPORT,
        CatalogWorkflowStageName.AI_ENRICHMENT,
        CatalogWorkflowStageName.PRODUCT_INTELLIGENCE_SCORE,
    }
)
