"""Catalog enrichment validation and warning vocabularies."""

from enum import StrEnum


class ClaimRiskCode(StrEnum):
    UNSUPPORTED_NUMERIC_CLAIM = "UNSUPPORTED_NUMERIC_CLAIM"
    UNSUPPORTED_UNIT_CLAIM = "UNSUPPORTED_UNIT_CLAIM"
    UNSUPPORTED_CERTIFICATION_CLAIM = "UNSUPPORTED_CERTIFICATION_CLAIM"
    UNSUPPORTED_WARRANTY_CLAIM = "UNSUPPORTED_WARRANTY_CLAIM"
    UNSUPPORTED_MATERIAL_CLAIM = "UNSUPPORTED_MATERIAL_CLAIM"
    UNSUPPORTED_PERFORMANCE_CLAIM = "UNSUPPORTED_PERFORMANCE_CLAIM"
    UNSUPPORTED_USE_CASE_CLAIM = "UNSUPPORTED_USE_CASE_CLAIM"
    UNKNOWN_FACT_REFERENCE = "UNKNOWN_FACT_REFERENCE"
    UNGROUNDED_CONTENT = "UNGROUNDED_CONTENT"


class EnrichmentWarningCode(StrEnum):
    UPSTREAM_PROJECTION_WARNING = "UPSTREAM_PROJECTION_WARNING"
    LOW_FACT_COVERAGE = "LOW_FACT_COVERAGE"
    ORIGINAL_DESCRIPTION_NOT_USED = "ORIGINAL_DESCRIPTION_NOT_USED"
    LIMITED_SOURCE_ATTRIBUTES = "LIMITED_SOURCE_ATTRIBUTES"
    HUMAN_OVERRIDE_PRESENT = "HUMAN_OVERRIDE_PRESENT"
    VALIDATION_WARNING_PRESENT = "VALIDATION_WARNING_PRESENT"
